### ISSUE TITLE
Quest 3 is not really solvable in one day

### ISSUE THREAD

**Issue by Serabe** [src-d/tutorial#2]
Quest 3 is not solvable in one hour unless we only want people to have a really basic understanding of who they are and what we do. Furthermore, this discourages discovering new things through links or investigating other project similar to what we do.

**Comment by jorgeschnura** [comment]
This is a good point. I'll encourage some additional investigation

**Comment by jorgeschnura** [comment]
Any interesting content in relation to them that comes to your mind?

**Comment by Serabe** [comment]
Difference engine, Bletchley Park, Bell Labs, Apollo XI, UTF-8...

**Comment by jorgeschnura** [comment]
Done
